### ISSUE TITLE
Generics are not supported

### ISSUE THREAD

**Issue by fuhrmanator** [Arezoo-Nasr/FamixTypeScriptImporter#4]
[TypeScript Generics](https://www.typescriptlang.org/docs/handbook/2/generics.html) are not currently supported, and importing a project with generics can cause a crash. 

```
Cannot read properties of undefined (reading 'getSubInheritances')
TypeError: Cannot read properties of undefined (reading 'getSubInheritances')
    at Inheritance.setSuperclass (C:\Users\Cris\Documents\GitHub\FamixTypeScriptImporter\src\lib\famix\src\model\famix\inheritance.ts:20:19)
    at C:\Users\Cris\Documents\GitHub\FamixTypeScriptImporter\src\ts2famix.ts:115:35
    at Array.forEach (<anonymous>)
    at C:\Users\Cris\Documents\GitHub\FamixTypeScriptImporter\src\ts2famix.ts:110:28
    at Array.forEach (<anonymous>)
    at TS2Famix.famixRepFromPath (C:\Users\Cris\Documents\GitHub\FamixTypeScriptImporter\src\ts2famix.ts:99:29)
    at Object.<anonymous> (C:\Users\Cris\Documents\GitHub\FamixTypeScriptImporter\src\ts2famix-cli.ts:17:26)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.m._compile (C:\Users\Cris\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1310:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
```

**Comment by fuhrmanator** [comment]
To support generics, the metamodel will have to be adapted as in parameterizable types in Java. But this requires significant study of generics in TypeScript.

In the short-term, it is possible to prevent the crashing of the tool. See 20acaf02eeb6982ba9eb86a527dc70b7081ada01

**Comment by fuhrmanator** [comment]
Partially fixed in #9 but need more tests
