### ISSUE TITLE
Cannot read property 'getName' of undefined

### ISSUE THREAD

**Issue by islemsaidani** [Arezoo-Nasr/FamixTypeScriptImporter#5]
TypeError: Cannot read property 'getName' of undefined
    at C:\Users\..\eclipse-workspace\parser-tsnode\FamixTypeScriptImporter\src\ts2famix.ts:69:94
    at Array.forEach (<anonymous>)
    at C:\Users\..\eclipse-workspace\parser-tsnode\FamixTypeScriptImporter\src\ts2famix.ts:51:23
    at Map.forEach (<anonymous>)
    at TS2Famix.famixRepFromPath (C:\Users\..\eclipse-workspace\parser-tsnode\FamixTypeScriptImporter\src\ts2famix.ts:47:32)
    at Object.<anonymous> (C:\Users\..\eclipse-workspace\parser-tsnode\FamixTypeScriptImporter\src\ts2famix-cli.ts:17:26)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Module.m._compile (C:\Users\..\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1371:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\..\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1374:12)

**Comment by fuhrmanator** [comment]
Thanks for reporting the bug.

Can you provide more information so that we can reproduce it? What project, what command, etc.

Also, a similar bug existed and was fixed before. Did you pull the latest changes of the tool?

**Comment by fuhrmanator** [comment]
According to Team 02, trying to import https://github.com/GuidovdRiet/typescript-game will also result in this error, with the following command:

```
ts-node src/ts2famix-cli.ts -i "../typescript-game/**/*.ts" -o project-model.json
```
